name: Strike Images
favicon: null
layout_spectrum: 0.5631338693201542
typography_spectrum: 0.11625607637688518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2371336908545345
  lightness: 0.9550903660710901
  saturation: 0.20868102088570595
  rhythmicContrast: 0.461318785790354
purpose: []
